### PR TITLE
fix: optional access to `Reflect.metadata`

### PR DESCRIPTION
**Pull request by sirenkovladd**
### 🔗 Linked issue

https://github.com/unjs/jiti/issues/145

### ❓ Type of change

replace `babel-plugin-transform-typescript-metadata`

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [X] 👌 Enhancement (improving an existing functionality like performance)
- [X] ✨ New feature (a non-breaking change that adds functionality)
- [X] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Replace all call Reflect.metadata with optional call (if not install `reflect-metadata`)

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for this PR i really appreciate it. 

Before moving forward with adding a fork, have you considered to make an upstream PR directly to babel?

Also in the meantime, would be nice if we inline the forked version of patch in jiti codebase (same as other plugin forks) but better maintainability.

Adding tests to the fixtures would be also awesome!

**Comment by sirenkovladd** [comment]
I already did this (https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/pull/70) over a month ago

the last activity in this repository was on March 4, 2022

**Comment by sirenkovladd** [comment]
We can move this repo to the `UnJS` organization

**Comment by pi0** [comment]
Moving to `src/plugins/babel-plugin-transform-typescript-metadata.ts` should be doable i guess. let me know if need help on this this.

**Comment by sirenkovladd** [comment]
Do you recommend moving all the code to `jiti`?

**Comment by pi0** [comment]
Source data only yes. (there are too many repos to maintain in unjs already and i hope we don't need constant update for this until your PR lands upstream -- hopefully)

**Comment by sirenkovladd** [comment]
One remark, there is a problem with pnpm, I suspect that it is install the types incorrectly
`build` works only with `npm install` and not `pnpm install`
do you have any idea?

**Comment by sirenkovladd** [comment]
```sh
❯ npm run build                     

> jiti@1.20.0 build
> pnpm clean && NODE_ENV=production pnpm webpack


> jiti@1.20.0 clean /home/sirenko/programming/jiti
> rm -rf dist

assets by status 2.12 MiB [cached] 12 assets
orphan modules 402 KiB [orphan] 31 modules
runtime modules 1.42 KiB 7 modules
cacheable modules 2.48 MiB
  modules by path ./node_modules/.pnpm/ 2.46 MiB
    javascript modules 2.43 MiB 399 modules
    json modules 30.7 KiB
      ./node_modules/.pnpm/globals@11.12.0/node_modules/globals/globals.json 29.7 KiB [built] [code generated]
      ./node_modules/.pnpm/@babel+preset-typescript@7.22.15_@babel+core@7.22.15/node_m...(truncated) 1010 bytes [built] [code generated]
  modules by path ./stubs/*.js 192 bytes
    ./stubs/babel-codeframe.js 52 bytes [built] [code generated]
    ./stubs/helper-compilation-targets.js 140 bytes [built] [code generated]
  ./src/babel.ts + 6 modules 20.1 KiB [built] [code generated]
+ 15 modules

ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-import-meta.ts
./src/plugins/babel-plugin-transform-import-meta.ts 29:25-38
[tsl] ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-import-meta.ts(29,26)
      TS2345: Argument of type 'babel.NodePath<import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").MemberExpression>' is not assignable to parameter of type 'babel.NodePath<babel.types.MemberExpression>'.
  Type 'import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").MemberExpression' is not assignable to type 'babel.types.MemberExpression'.
    Types of property 'object' are incompatible.
      Type 'import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").Expression' is not assignable to type 'babel.types.Expression'.
        Type 'ArrayExpression' is not assignable to type 'Expression'.
          Type 'import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").ArrayExpression' is not assignable to type 'babel.types.ArrayExpression'.
            Types of property 'elements' are incompatible.
              Type '(SpreadElement | Expression | null)[]' is not assignable to type '(Expression | SpreadElement | null)[]'.
                Type 'SpreadElement | Expression | null' is not assignable to type 'Expression | SpreadElement | null'.
                  Type 'ArrayExpression' is not assignable to type 'Expression | SpreadElement | null'.
 @ ./src/babel.ts 2:0-89 13:13-38

ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-typescript-metadata/index.ts
./src/plugins/babel-plugin-transform-typescript-metadata/index.ts 31:33-37
[tsl] ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-typescript-metadata/index.ts(31,34)
      TS2345: Argument of type 'babel.NodePath<import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").ClassDeclaration>' is not assignable to parameter of type 'babel.NodePath<babel.types.ClassDeclaration>'.
  Type 'import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").ClassDeclaration' is not assignable to type 'babel.types.ClassDeclaration'.
    Types of property 'id' are incompatible.
      Type 'Identifier | null | undefined' is not assignable to type 'Identifier'.
        Type 'undefined' is not assignable to type 'Identifier'.
 @ ./src/babel.ts 4:0-106 24:31-69

ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-typescript-metadata/index.ts
./src/plugins/babel-plugin-transform-typescript-metadata/index.ts 32:32-36
[tsl] ERROR in /home/sirenko/programming/jiti/src/plugins/babel-plugin-transform-typescript-metadata/index.ts(32,33)
      TS2345: Argument of type 'babel.NodePath<import("/home/sirenko/programming/jiti/node_modules/.pnpm/@babel+types@7.22.17/node_modules/@babel/types/lib/index").ClassDeclaration>' is not assignable to parameter of type 'babel.NodePath<babel.types.ClassDeclaration>'.
 @ ./src/babel.ts 4:0-106 24:31-69

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.2 compiled with 3 errors in 9278 ms
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/home/sirenko/programming/jiti/dist/jiti.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/sirenko/programming/jiti/dist/jiti.js'
}

Node.js v20.6.0
```

**Comment by sirenkovladd** [comment]
Ok, I just hate pnpm lock, it's ok now

**Comment by sirenkovladd** [comment]
@pi0 what do you think about it now?

**Comment by pi0** [comment]
Thanks for the updates! Will check it soon locally 👍🏼

**Comment by sirenkovladd** [comment]
@pi0 hi, how's your check going?

**Pull request merged**
