### PR TITLE
fix: add support to emit decorator metadata

### LINKED ISSUE #118: Reflect Metadata
### Environment

Nodejs: v16.16.0
Jiti Version: 1.17.1

### Reproduction

Try to transpile any code with decorators which depend on dependency injection (e.g. typeorm, ..)

### Describe the bug

At the moment the implementation just strips all types and does not emit the relative Metadata in the output code.
Therefore, we also need the plugin [babel-plugin-transform-typescript-metadata](https://www.npmjs.com/package/babel-plugin-transform-typescript-metadata) to emit decorator metadata like the typescript compiler does.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by tada5hi**
closes #118

### CODE REVIEW

**Comment by pi0** [comment]
Thanks 🙏 can you please add fixtures too?

**Comment by tada5hi** [comment]
@pi0 very very much and is done. I hope it fits so ;)

**Comment by tada5hi** [comment]
Let me know if something is missing

**Review by pi0 — APPROVED** [review]
Thanks!

**Pull request merged**
